spring.application.name=ToDoList

# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/focolist?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=MysqlServer_11
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.messages.basename=messages/errors
spring.messages.encoding=ISO-8859-1